### ISSUE TITLE
Rainbow-colored zodiac symbols

### ISSUE THREAD

**Issue by Crissov** [emojione/emojione-assets#19]
Google's Android O(reo) preview has its zodiac symbol emojis colored much like Emojione 2. You should consider to re-introduce them to version 3.1+.

### Google Android O preview (Noto Emoji)
![aries](https://cloud.githubusercontent.com/assets/6200185/26346103/6ec4ce30-3fa5-11e7-87fd-b8cfeca10f71.png) ![taurus](https://cloud.githubusercontent.com/assets/6200185/26346081/5f8530ae-3fa5-11e7-9f3a-7b555d2e8c1e.png) ![gemini](https://cloud.githubusercontent.com/assets/6200185/26346119/7da57012-3fa5-11e7-89ac-9ce0a2940212.png) ![cancer](https://cloud.githubusercontent.com/assets/6200185/26346135/8b340fcc-3fa5-11e7-9b6d-505ae4568e07.png) ![leo](https://cloud.githubusercontent.com/assets/6200185/26346151/981e68c2-3fa5-11e7-9096-7ae2759b7e0c.png) ![virgo](https://cloud.githubusercontent.com/assets/6200185/26346166/a74c08fe-3fa5-11e7-8a78-a1acbb763b0a.png) ![libra](https://cloud.githubusercontent.com/assets/6200185/26346173/ad2af7ee-3fa5-11e7-9463-78f7b52bd84b.png) ![scorpius](https://cloud.githubusercontent.com/assets/6200185/26346199/be35c942-3fa5-11e7-9a5d-91c816772284.png) ![sagittarius](https://cloud.githubusercontent.com/assets/6200185/26346215/c9b55c74-3fa5-11e7-9e0e-45e1de87a662.png) ![capricorn](https://cloud.githubusercontent.com/assets/6200185/26346245/df918c20-3fa5-11e7-9e57-2b7fb742e061.png) ![aquarius](https://cloud.githubusercontent.com/assets/6200185/26346262/ee90b96c-3fa5-11e7-9004-6983dc7b8b7d.png) ![pisces](https://cloud.githubusercontent.com/assets/6200185/26346286/fc1540b2-3fa5-11e7-96c2-a72ebd43ed6b.png)

### Emojione 2.2 = Emojitwo
![](https://rawgit.com/EmojiTwo/emojitwo/master/png/2648.png) ![](https://rawgit.com/EmojiTwo/emojitwo/master/png/2649.png) ![](https://rawgit.com/EmojiTwo/emojitwo/master/png/264a.png) ![](https://rawgit.com/EmojiTwo/emojitwo/master/png/264b.png) ![](https://rawgit.com/EmojiTwo/emojitwo/master/png/264c.png) ![](https://rawgit.com/EmojiTwo/emojitwo/master/png/264d.png) ![](https://rawgit.com/EmojiTwo/emojitwo/master/png/264e.png) ![](https://rawgit.com/EmojiTwo/emojitwo/master/png/264f.png) ![](https://rawgit.com/EmojiTwo/emojitwo/master/png/2650.png) ![](https://rawgit.com/EmojiTwo/emojitwo/master/png/2651.png) ![](https://rawgit.com/EmojiTwo/emojitwo/master/png/2652.png) ![](https://rawgit.com/EmojiTwo/emojitwo/master/png/2653.png)

### Emojione 3.0
![](https://rawgit.com/Ranks/emojione-assets/master/png/64/2648.png) ![](https://rawgit.com/Ranks/emojione-assets/master/png/64/2649.png) ![](https://rawgit.com/Ranks/emojione-assets/master/png/64/264a.png) ![](https://rawgit.com/Ranks/emojione-assets/master/png/64/264b.png) ![](https://rawgit.com/Ranks/emojione-assets/master/png/64/264c.png) ![](https://rawgit.com/Ranks/emojione-assets/master/png/64/264d.png) ![](https://rawgit.com/Ranks/emojione-assets/master/png/64/264e.png) ![](https://rawgit.com/Ranks/emojione-assets/master/png/64/264f.png) ![](https://rawgit.com/Ranks/emojione-assets/master/png/64/2650.png) ![](https://rawgit.com/Ranks/emojione-assets/master/png/64/2651.png) ![](https://rawgit.com/Ranks/emojione-assets/master/png/64/2652.png) ![](https://rawgit.com/Ranks/emojione-assets/master/png/64/2653.png)

**Comment by kevinranks** [comment]
The input and suggestion is appreciated, but I don't see a good argument for going back to rainbow colored zodiac symbols.
