### ISSUE TITLE
Provide Head and Body Images for all Animals

### ISSUE THREAD

**Issue by caseyahenson** [emojione/emojione-assets#21]
From: @crissov
Original issue: https://github.com/emojione/emojione/issues/419

**Comment by thinkrick** [comment]
Thx for the detailed feedback, and seriously awesome charts.

That's an interesting idea about providing both the face and body, letting vendors then decide. Logistically isn't as easy as it might seem and ultimately we have to force one specific design in the default set. Our resources are still pretty thin and we have to invest them toward the areas in highest demand. This is the first time we've had this specific request, and a clever idea. Most likely there won't be any action for now, but it's something we'll consider for future development. 🕺

Thank you Crissov!
