### ISSUE TITLE
v3.1 sprites

### ISSUE THREAD

**Issue by workmanw** [emojione/emojione-assets#23]
We just bought a premium license of emojione today. It seems just after v3.1 shipped. So I'm sure v3.1 sprites are coming, but I was curious what the timeline looks like for that.

**Comment by kevinranks** [comment]
@workmanw Good timing! I pushed up the 3.1 sprites to the repo this morning and we'll be publishing the official release today or tomorrow. :smile:.

**Comment by workmanw** [comment]
@kevinranks You guys rock! Thanks a lot.
