### ISSUE TITLE
Rename png files to include ZWJ

### ISSUE THREAD

**Issue by maximbaz** [emojione/emojione-assets#24]
See https://github.com/emojione/emojione/issues/524 for more details.

---------------

In order to correctly build emoji font we have to rename image files to include `200d` in them. Otherwise the resulting font cannot distinguish between two separate emojis and a single "complex" emoji:

Font built with current image files:

![image](https://user-images.githubusercontent.com/1177900/27875840-fa590552-61b4-11e7-8b64-541b5751c885.png)

Font built with renamed image files:

![image](https://user-images.githubusercontent.com/1177900/27875789-c5f59852-61b4-11e7-9fa5-58836108a722.png)

We have identified the following renaming rules (they can be applied multiple times to the same png file):

```
-1f308 => -200d-1f308
-1f33e => -200d-1f33e
-1f373 => -200d-1f373
-1f393 => -200d-1f393
-1f3a4 => -200d-1f3a4
-1f3a8 => -200d-1f3a8
-1f3eb => -200d-1f3eb
-1f3ed => -200d-1f3ed
-1f466 => -200d-1f466
-1f467 => -200d-1f467
-1f468 => -200d-1f468
-1f469 => -200d-1f469
-1f48b => -200d-1f48b
-1f4bb => -200d-1f4bb
-1f4bc => -200d-1f4bc
-1f527 => -200d-1f527
-1f52c => -200d-1f52c
-1f5e8 => -200d-1f5e8
-1f680 => -200d-1f680
-1f692 => -200d-1f692
-2642  => -200d-2642
-2695  => -200d-2695
-2696  => -200d-2696
-2708  => -200d-2708
-2764  => -200d-2764
```

However it is easy to make a manual mistake, plus these rules are not permanent and will change as new emojis are released. That's why I'm asking to consider renaming the files in this repo (unless you have special reasons not to do it).

You have the `emoji.json` file with `base` and `output` codepoints, but neither of them defines the correct file name for a png file. For example, the `woman mage` file must be named `1f9d9-200d-2640`, not `1f9d9-2640` (as per base code points) and not `1f9d9-200d-2640-fe0f` (as per full code points). If there is a reason not to rename files, could you at least consider adding the correct file name to the `emoji.json`, so we can script the renaming process?

**Comment by caseyahenson** [comment]
@maximbaz what we're going to do here is break the `code_points` attribute down to be a little bit more specific. We'll add the `fully_qualified` and `non_fully_qualified` code points to that attribute, which is based upon the data here: http://unicode.org/Public/emoji/5.0/emoji-test.txt.

Obviously you guys have done the bulk of the work already in renaming but we'll have an updated file out to the repo within a day or two.

**Comment by maximbaz** [comment]
The new emoji.json file contains now `non_fully_qualified` property and this is exactly what we need to use as file names. Thanks, problem solved 🙂
