### ISSUE TITLE
Automatically build fonts on every tagged release (I made a Docker image)

### ISSUE THREAD

**Issue by maximbaz** [emojione/emojione-assets#25]
Building fonts is a rather complicated process, only a few had time and desire to dig into this and understand how it works, thus you rely on community to provide the fonts for every release. But this whole process shouldn't be that complicated!

I made [a Docker image to build fonts](https://github.com/maximbaz/docker-emojione-fonts-build) (Android/Linux only for now). It has all the dependencies built in, so anyone on any platform can build a font out of the latest `emojione-assets` using just these two commands:

```
$ docker pull maximbaz/emojione-fonts-build
$ docker run --rm -v $(pwd):/fonts maximbaz/emojione-fonts-build
```

However we can do even better! 

I'm suggesting to create a Travis job for `emojione-assets` repository, that will [run automatically every time you create a tag](https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A), build the font files and attach them to [your releases](https://github.com/emojione/emojione-assets/releases). 

I'm totally willing to help with setting this up. Do you like the idea?

------------

I made the Docker image with the idea of adding more target fonts in the future. For example, if someone wants to contribute building `emojione-apple.tt*`, they only need to add build dependencies to the [Dockerfile](https://github.com/maximbaz/docker-emojione-fonts-build/blob/master/Dockerfile) and the build command itself to the [build.sh](https://github.com/maximbaz/docker-emojione-fonts-build/blob/master/build.sh).

-----------

There's obviously a dependency on naming the font files properly #24, for now [the files are renamed](https://github.com/maximbaz/docker-emojione-fonts-build/blob/ed1010a16b433e5d61f8ba90a98632d32b5b22e9/build.sh#L13-L18) according to the patterns discovered manually.

---------

/cc @caseyahenson, @mxalbert1996, @vXBaKeRXv

**Comment by vXBaKeRXv** [comment]
Apples emoji is supper hectic when it comes to adding in glyphs or rebuilding all tables based off of image names. If you add a glyph in without fixing morx, it shifts the ligatures. Took me awhile to figure out how because it takes multiple steps and you need FF. 

I've Ben waiting for years for FontTools to add support morx table. You can use GSUB instead but morx is the standard with sbix. When this happens, then I think it will possible to build fonts similar to googles Noto emoji project and this here would be a great solution.

**Comment by maximbaz** [comment]
FYI the issue https://github.com/emojione/emojione-assets/issues/24 is solved and the docker image is now renaming files according to the `non_fully_qualified` property in `emoji.json`. 

This is ready to be incorporated in this repo as a Travis job that builds fonts automatically on every tagged release. Let me know if you want this, and I'll help you to set everything up.

**Comment by kevinranks** [comment]
@maximbaz Big thanks for putting this together! We've debated in the past about which repo the font files belong in. We intended for this assets repo to be for artwork only, with the main emojione repo being used for supplementary scripts and files. With that said, we're open to suggestion and whatever the community feels would best serve them.

What do you need me to go to get this going?

**Comment by maximbaz** [comment]
It is much easier to make Travis attach built fonts to this repo rather than emojione repo (see also #30). Maybe it will be a sufficient workaround that you guys manually copy the built font file from this repo into emojione repo?

**Comment by kevinranks** [comment]
It appears that the size of the font files may be an issue for our free cdn provider jsdelivr anyways, and they're recommending that we take the font files out of the main emojione repo. Looks like moving the fonts to this repo might work out better.

**Comment by maximbaz** [comment]
Even better then 🙂 Let's continue in #30
