### ISSUE TITLE
sprites .css files using the wrong media queries for high resolution displays on Firefox

### ISSUE THREAD

**Issue by lepolt** [emojione/emojione-assets#26]
This can be seen in the wild with Firefox here: https://www.emojione.com/emoji/v3. The emojis are blurry on a MacBook Pro Retina display because they aren't using the @2x styles. MDN docs (https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#-moz-device-pixel-ratio) suggest using `min-resolution: 2dppx`, but also might need a fallback to 192dpi. 

Using Firefox 54.x

Followup, I would submit a PR to help with this, but I wasn't sure how you generate the final .CSS files...is it automated, or do you build them by hand?

**Comment by cspicuzza** [comment]
@lepolt thanks for the suggestion!  It has been merged in.
