### ISSUE TITLE
Trigger Travis to build ttf font

### ISSUE THREAD

**Issue by maximbaz** [emojione/emojione-assets#34]
Congrats on v4 release!

@caseyahenson looks like you tagged a commit from Github UI and that didn't trigger Travis build... Could you please either trigger Travis build manually or tag master and push this tag? You can remove that tag afterwards. 

Writing from memory:

git pull
git tag release-4.0
git push --tags

If everything goes as planned, emojione-android.ttf will be attached to your release in 10 mins.

Thanks!

**Comment by caseyahenson** [comment]
Thanks @maximbaz! Just pushed that tag, hopefully that does it :)

**Comment by maximbaz** [comment]
I see the font is being built successfully, but Travis has issues attaching it to the release, looks like Github's API has changed.

https://travis-ci.org/emojione/emojione-assets/builds

I'll have a look tomorrow, at the very least I'll send you the ttf file so you can attach it manually.

**Comment by caseyahenson** [comment]
Sounds great! 🙏

**Comment by maximbaz** [comment]
It looks like a transient issue with Travis, people have reported this before, but nobody is investigating.
https://github.com/travis-ci/travis-ci/issues/9441

In fact, Travis was triggered when you created a release via UI, so feel free to remove the `release-4.0` tag and in future publish releases like you did yesterday via UI, it should work.

Here's a ttf file (had to zip it, because Github is annoying), just unarchive and attach it to your release, and close this issue. Emojis look awesome, by the way 😉 

[emojione-android.ttf.zip](https://github.com/emojione/emojione-assets/files/2335738/emojione-android.ttf.zip)

**Comment by caseyahenson** [comment]
Done and done. Thank you!!

**Comment by maximbaz** [comment]
Awesome, and I've just updated the package for Arch Linux to include your new font 😉 
By the way, you can close #32 as it is completely obsolete now.

Also, I'd like to use this opportunity to sneak in my personal request to you @caseyahenson, I was updating an app to use the latest emojis when I stumbled upon https://github.com/emojione/emojione/issues/612, if you could have a look I would be very grateful.

Thanks 😉

**Comment by maximbaz** [comment]
Don't forget to update the website 😝 

![image](https://user-images.githubusercontent.com/1177900/45046072-58116f80-b075-11e8-9db7-6e4608e66645.png)
