### ISSUE TITLE
Android ttf pistol

### ISSUE THREAD

**Issue by neekless** [emojione/emojione-assets#35]
I know you have 2 versions of pistol: a more realistic pistol and a water pistol. The android ttf is using the realistic pistol. Are there plans to release a water pistol version of the ttf?

**Comment by maximbaz** [comment]
I'm not part of the team, but it was me who built the ttf font and as far as I know this repo contains the image [only for realistic pistol](https://github.com/emojione/emojione-assets/blob/master/png/128/1f52b.png). If the team points me to the water pistol images, I can easily compile an alternative ttf font for you, and perhaps we can attach this alternative ttf file to the release as well.

**Comment by neekless** [comment]
hey @maximbaz thanks for building the ttf! I learned about the water pistol from [here](https://www.emojione.com/blog/emojione-to-include-both-water-gun-pistol-emoji-in-version-40) but you're right that this repo doesn't have the image. Hope the team can add it soon.

**Comment by caseyahenson** [comment]
We can definitely publish the `_alt` directory here as we do on the [downloads](https://www.emojione.com/download) page. @maximbaz would you be able to parse out alternatives with that structure? Currently we only publish the pistol alternative but there may be more (similarly PG) in the future that could be written into an alternative font.

**Comment by maximbaz** [comment]
That won't be a problem at all, but I would like you to think about how many alternative fonts would you like to have. Let's say you have 3 images in the `_alt` directory: A, B and C. Would you like to have 2 fonts in total (one based on default images, one contains all 3 alternative emoji), or would you rather have full matrix, i.e. 8 fonts in total (default, default with A, with B, with C, with A and B, with B and C, with A and C, and with A and B and C)?

**Comment by Crissov** [comment]
Single font with `hist`, `locl`, `ss01`…, `cv01`…, `calt` as appropriate?

**Comment by maximbaz** [comment]
I don't know these abbreviations 🙊  Are you suggesting that ttf font can itself handle alternative images of the same glyph? But how would it work from a user perspective, how would they choose which image they prefer to see? 🤔 

Also, to be completely transparent, I don't know exactly how the build script works, I am not sure I will be able to modify it appropriately — but if this approach is preferable, patches would be very welcome 🙂 

@mxalbert1996 is the author of the build scripts, see code [here](https://github.com/mxalbert1996/emojione-android). I merely [forked](https://github.com/maximbaz/emojione-android) their repo, removed hardcoded assets and wrapped everything in a Docker container that is executed against assets in this repo on every tagged commit 🙂

**Comment by mxalbert1996** [comment]
I have updated my [repo](https://github.com/mxalbert1996/emojione-android) and added [ttf font with watergun](https://github.com/mxalbert1996/emojione-android/raw/master/fonts/EmojiOne_Watergun.ttf).
BTW, AFAIK, unless Unicode defines different codepoints for the two types of pistol, it is not realistic to include both pistols in one font.

**Comment by Crissov** [comment]
The four-letter codes I mentioned are Open Type tables that are intended to take care of displaying alternative glyphs. Some of them need to be manually invoked by the user, e.g. `hist` is for older variants, others can work automatically, e.g. `locl` depends on the content language and `calt` on neighboring glyphs.

**Comment by caseyahenson** [comment]
Nice @mxalbert1996! I'll be adding the `_alt` directory into this repo by end of week, and to answer your question @maximbaz regardless of how many alternative emoji we release we'll still be keeping it simple by promoting just one alternative font.
