### ISSUE TITLE
Luxembourg flag emoji inaccurate

### ISSUE THREAD

**Issue by caseyahenson** [emojione/emojione-assets#8]
From: @mikeparadinas
Original issue: https://github.com/Ranks/emojione/issues/348

**Comment by Crissov** [comment]
Emojione 3.0: ![NL](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f1f1-1f1fa.png) ![LU](https://rawgit.com/Ranks/emojione-assets/master/png/64/1f1f3-1f1f1.png)
Emojione 2.x: ![NL](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f1f1-1f1fa.png) ![LU](https://rawgit.com/Ranks/emojione/2.2.7/assets/png/1f1f3-1f1f1.png)

**Comment by mikeparadinas** [comment]
sweet

**Comment by kevinranks** [comment]
I believe we can close this now. The new Netherlands flag is visibly darker.
